ktor {
  deployment {
    port = 8080
    port = ${?PORT}
  }

  application {
    modules = [ com.nukinderuru.ApplicationKt.module ]
  }
}

database {
  driverClassName = "org.postgresql.Driver"
  jdbcUrl = "jdbc:postgresql://localhost:5432/shop"
  jdbcUrl = ${?DATABASE_JDBC_URL}
  username = "shop_user"
  username = ${?DATABASE_USERNAME}
  password = "shoppass"
  password = ${?DATABASE_PASSWORD}
  maximumPoolSize = 10
  maximumPoolSize = ${?DATABASE_MAXIMUM_POOL_SIZE}
}

auth {
  host = "localhost"
  host = ${?AUTH_SERVICE_HOST}
  port = 9090
  port = ${?AUTH_SERVICE_PORT}
}
